language: python

python:
  - "2.7"

env:
  - TOXENV=py27-1.4.X
  - TOXENV=py27-1.5.X,py32-1.5.X
  - TOXENV=py27-1.5.X-swapped,py32-1.5.X-swapped
  - TOXENV=py27-1.6.X,py32-1.6.X
  - TOXENV=py27-1.6.X-swapped,py32-1.6.X-swapped
  - TOXENV=py27-1.7.X,py32-1.7.X
  - TOXENV=py27-1.7.X-swapped,py32-1.7.X-swapped
  - TOXENV=py27-1.8.X,py32-1.8.X
  - TOXENV=py27-1.8.X-swapped,py32-1.8.X-swapped

install:
  - pip install tox

script:
    - tox

branches:
  only:
    - master
